# Currently, the diagnostic supports comparing one dataset against one reference dataset at a time.
datasets:
  - catalog: null
    model: null
    exp: null
    source: null
    regrid: null
    reader_kwargs: null # it can be a dictionary with reader kwargs
    startdate: null
    enddate: null

setup:
  loglevel: 'WARNING'

output:
  outputdir: "./"
  rebuild: true
  save_netcdf: true
  save_pdf: true
  save_png: true
  dpi: 300
  create_catalog_entry: true

diagnostics:
  EnsembleLatLon:
    run: true
    diagnostic_name: 'atmosphere2d'
    variable: ['2t','msl']
    params:
      default:
      tprate:
        standard_name: "tprate"
        long_name: "Precipitation"
        units: "mm/day"
    plot_params:
      default:
        projection: 'robinson'
        projection_params: {}
      2t:
        vmin:
        vmax: 
        vmin_std: 
        vmax_std: 
        cmap: 'RdBu_r'
      msl:
        vmin: 
        vmax: 
        vmin_std: 
        vmax_std: 
      tprate:
        vmin: 
        vmax: 
        vmin_std: 
        vmax_std:

  EnsembleTimeseries:
    run: true
    diagnostic_name: 'atmosphere2d'
    variable: ['2t',]
    region: ['global',]
    params:
      default:
        startdate_data: "1990-01-16"
        enddate_data: "2014-11-16"
        startdate_ref: "1990-01-16"
        enddate_ref: "2014-11-16"
    plot_params:
      default:
        title: 
        plot_ensemble_members: True

