# Currently, the diagnostic supports comparing one dataset against one reference dataset at a time.
datasets:
  - catalog: 'climatedt-o25.1'
    model: 'IFS-NEMO'
    exp: 'hist-1990-ensemble'
    source: 'aqua-ocean2d-annual_climatology'
    regrid: null
    #areas: False
    #fix: True

setup:
  loglevel: 'WARNING'

output:
  outputdir: "./"
  rebuild: true
  save_netcdf: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostics:
  EnsembleLatLon:
    run: true
    diagnostic_name: 'ocean2d'
    variable: ['tos']
    params:
      default:
    plot_params:
      default:
        projection: 'robinson'
        projection_params: {}
      tos:
        vmin:
        vmax: 
        vmin_std: 
        vmax_std: 
        cmap: 'RdBu_r'

