sources:
# p000 ensemble
  p000-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p000
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: avg_tos
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      # variables: ['avg_tos', 'avg_hc300m']
      variables: ['263100', '263101', '263122', '263121', '263001']
      source_grid_name: lon-lat
  p000-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p000
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p001 ensemble
  p001-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p001
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p001-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p001
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p002 ensemble
  p002-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p002
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p002-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p002
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p003 ensemble
  p003-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p003
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p003-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p003
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p004 ensemble
  p004-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p004
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p004-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p004
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p005 ensemble
  p005-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p005
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p005-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p005
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p006 ensemble
  p006-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p006
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p006-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p006
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p007 ensemble
  p007-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p007
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p007-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p007
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p008 ensemble
  p008-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p008
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p008-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p008
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

# p009 ensemble
  p009-monthly-1deg-2d:
    args:
      request:
        domain: g
        class: rd
        expver: p009
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        param: sd
        levtype: o2d
        grid: "1/1"
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: Y  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_sos', 'avg_tos', 'avg_hc300m']
      source_grid_name: lon-lat
  p009-monthly-1deg-3d:
    args:
      request:
        domain: g
        class: rd
        expver: p009
        type: fc
        stream: monr
        date: 19900101
        time: '0000'
        grid: "1/1"
        param: t
        levtype: o3d
        levelist: [1, 5, 10, 20, 30, 50, 70, 100, 150, 200, 250, 300, 400, 500, 600,
          700, 850, 925, 1000]
        step: 0
      data_start_date: '19900101'
      data_end_date: '20180401'
      aggregation: M  # Default aggregation / chunk size
      timestep: H
      savefreq: M
      timestyle: step
      timeshift: Yes    # shift time of resulting xarray by this amount
    description: monthly data on r100 grid. 
    driver: gsv
    metadata:
      fdb_path: /pfs/lustrep3/scratch/project_465000454/kaikeller/a0eo/config.yaml
      eccodes_path: /pfs/lustrep3/projappl/project_465000454/models/ifs-nemo/DE_CY48R1.0_climateDT_develop/source/eccodes/definitions/
      variables: ['avg_so', 'avg_thetao', 'avg_wo', 'avg_uoe', 'avg_von']
      source_grid_name: lon-lat

