sources:
  fdb-tco79-eorca1:
    description: tco79-eorca1 from Bernat to test FDB-NEMO access
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/fdb-tco79-eorca1.yaml"
  control-1990-nemo-dev:
    description: FDB IFS/NEMO tco1279-orca025 historical 1990 run
    driver: yaml_file_cat
    args:
      path: '{{CATALOG_DIR}}/control-1990-nemo-dev.yaml'
  a0er-LUMI-C:
    description: a0er-LUMI-C
    driver: yaml_file_cat
    args:
      path: '{{CATALOG_DIR}}/a0er-LUMI-C.yaml'
  a0eo-LUMI-G:
    description: a0eo-LUMI-G
    driver: yaml_file_cat
    args:
      path: '{{CATALOG_DIR}}/a0eo-LUMI-G.yaml'
  a0hy-LUMI-G:
    description: a0hy-LUMI-G
    driver: yaml_file_cat
    args:
      path: '{{CATALOG_DIR}}/a0hy-LUMI-G.yaml'
