sources:
  fdb-tco79-eorca1:
    description: tco79-eorca1 from Bernat to test FDB-NEMO access
    driver: yaml_file_cat
    args:
        path: "{{CATALOG_DIR}}/fdb-tco79-eorca1.yaml"
  control-1990-nemo-dev:
    description: FDB IFS/NEMO tco1279-orca025 historical 1990 run
    driver: yaml_file_cat
    args:
      path: '{{CATALOG_DIR}}/control-1990-nemo-dev.yaml'

  a0eo-LUMI-G-IFS-NEMO-10ensembles:
    description: FDB IFS/NEMO tco1279-orca025 control 1990 run
    driver: yaml_file_cat
    args:
      path: '{{CATALOG_DIR}}/a0eo-LUMI-G-IFS-NEMO-10ensembles.yaml'

        path: '{{CATALOG_DIR}}/fdb-tco79-eorca1.yaml'
